version: "2"
services:
  object_detection:
    image: turnerlabs/object-detection-docker
    ports:
    - 80:5000
    environment:
      PORT: 5000
      THRESHOLD: 0.6
      DEBUG: "True"
      NUM_CLASSES: 1
    volumes:
       - ./frozen_inference_graph.pb:/opt/graph_def/frozen_inference_graph.pb
       - ./santa_label_map.pbtext:/opt/configs/data/santa_label_map.pbtext
