version: "2"
services:
  object_detection:
    image: object-detection-docker
    ports:
    - 5000:5000
    environment:
      PORT: 5000
      THRESHOLD: 0.6
      DEBUG: "True"
      NUM_CLASSES: 1
      PYTHONUNBUFFERED: 1
      SECRET_KEY: "${SECRET_KEY}"
      ACCESS_KEY: "${ACCESS_KEY}"
      BUCKET: "${BUCKET}"
      CKPT_S3_FILE: "${CKPT_S3_FILE}"
      LABEL_S3_FILE: "${LABEL_S3_FILE}"
