version: "2"
services:
  object_detection:
    image: object-detection-docker
    ports:
    - 80:80
    environment:
      PORT: "80"
    volumes:
       - ./frozen_inference_graph.pb:/opt/graph_def/frozen_inference_graph.pb
       - ./santa_label_map.pbtext:/opt/configs/data/santa_label_map.pbtext
